---
title: "The Annual Calendar"
description: | 
  A sketch of the typical year for students who like the great outdoors.
keywords:
  - warwick university
  - warwick university climbers union
  - climbing
  - students
  - union
  - outdoor climbing
  - warwick sport
  - warwick students union
  - mountaineering
  - calendar
  - trips
  - warwick mountains
  - warwick university climbing club
output: 
  distill::distill_article:
    css: style.css
---

<style>
body {
text-align: justify}
</style>

Below is a rough sketch of the typical year in the University of Warwick outdoor community calendar, including the big trips and events. Trips are run by three clubs: [Warwick University Climbing Club (WUCC)](https://www.warwicksu.com/societies-sports/sports-clubs/climbing/){target="_blank"}, [Warwick Mountains](https://www.warwicksu.com/societies-sports/sports-clubs/mountains/){target="_blank"} and us, Warwick University Climbers' Union (WUCU). The first two clubs are affiliated with the Students' Union, so if you join one of WUCC or Warwick Mountains then you need to pay for the [Sports Federation and for the Warwick SU Club Pass](https://www.warwicksu.com/societies-sports/sports-clubs/howtojoin/){target="_blank"}. Once you've paid for these it only costs a very small amount (£6 ish) to join any other sports club; so you might as well join the other club as well. In previous years keen climbers have joined both clubs and taken advantage of all the trips on offer; you only get one life, after all. If you are a beginner climber then it is definitely worth joining both, as they each teach different sets of skills that complement each other.

During Term 1, WUCC will teach you how to [climb and belay with a top-rope](https://www.youtube.com/watch?v=tGiGw_XnSW0){target="_blank"} and Warwick Mountains will teach you how to [navigate in UK mountain areas](https://www.youtube.com/watch?v=WMO1Qz-kH4Q){target="_blank"}. Over new year, Warwick Mountains Scotland tour takes place where you will learn to stay safe in UK mountains in winter conditions. During Term 2, WUCC will teach you how to [lead climb and belay](https://www.youtube.com/watch?v=UI0cnk_k0eI){target="_blank"} and take you outside to practice your skills, before putting them to the test on their European Tour over the Easter Break.  During Term 1 of your second year WUCC will teach you how to [climb in traditional style](https://www.youtube.com/watch?v=TzNH5dm1bGo){target="_blank"}. If you learn how to climb and mountaineer in your first year, and learn trad skills during Term 1 of your second year, then during your second Warwick Mountains Scotland Tour then you will be able to learn how to do [winter scrambling and low grade winter climbing](https://www.youtube.com/watch?v=8P6yUjYRqxU){target="_blank"}.

WUCC Trips tend to be posted on its [Facebook group](https://www.facebook.com/groups/213573838712663){target="_blank"} as well as organised via email. All Warwick Mountains Trips are organised via email.

WUCU Trips are more ad-hoc and are organised via our [Facebook group](https://www.facebook.com/groups/3206887099412017){target="_blank"}.

## Term 1
### Start
* [WUCU / WUCC Trip to Compton Verney](https://www.youtube.com/watch?v=osGrr3xg3NA){target="_blank"}
* [WUCC Taster Bouldering Trip to the Ballroom, Coventry](https://www.facebook.com/events/2664292006943905/?acontext=%7B%22event_action_history%22%3A[%7B%22surface%22%3A%22group%22%7D]%7D){target="_blank"}
* Warwick Mountains Day Trip - Usually to the Peak District
* Warwick Mountains Day Trip - Usually to Shropshire

### Middle
* Warwick Mountains - Official Mountain Marathon
* [WUCC Trip - Usually to North Yorkshire](https://www.facebook.com/events/172940950261335/?acontext=%7B%22event_action_history%22%3A[%7B%22surface%22%3A%22group%22%7D]%7D){target="_blank"}
* Warwick Mountains Trip - Usually to North Wales
* [WUCC Freshers' Trip](https://www.facebook.com/events/246300932907708/?acontext=%7B%22event_action_history%22%3A[%7B%22surface%22%3A%22group%22%7D]%7D){target="_blank"}

### End
* Warwick Mountains Trip - Usually the Lake District
* [Warwick Mountains Scotland Winter Tour](https://www.warwickmountains.com/scotland-tour){target="_blank"}

## Term 2
### Start
* Warwick Mountains Trip - Usually to the Lake District

### Middle
* [WUCC Beginner Lead Trip - North Wales](https://www.facebook.com/events/2175304419396695/?acontext=%7B%22event_action_history%22%3A[%7B%22surface%22%3A%22group%22%7D]%7D){target="_blank"}
* Warwick Mountains Trip - Usually to Wales
* [WUCC Beginner Lead Trip - Cheddar Gorge](https://www.facebook.com/events/347364355869879/?acontext=%7B%22event_action_history%22%3A[%7B%22surface%22%3A%22group%22%7D]%7D){target="_blank"} or [Portland](https://www.facebook.com/events/2175304419396695/?acontext=%7B%22event_action_history%22%3A[%7B%22surface%22%3A%22group%22%7D]%7D){target="_blank"}
* [Warwick vs Coventry Varsity Bouldering Competition](https://www.facebook.com/events/538429459983640/?acontext=%7B%22event_action_history%22%3A[%7B%22surface%22%3A%22group%22%7D]%7D){target="_blank"}

### End
* [WUCC Open Competition](https://www.facebook.com/events/377428732807398/?acontext=%7B%22event_action_history%22%3A[%7B%22surface%22%3A%22group%22%7D]%7D){target="_blank"}
* [WUCC and Warwick Mountains Bevathlon](https://www.facebook.com/events/377428732807398/?acontext=%7B%22event_action_history%22%3A[%7B%22surface%22%3A%22group%22%7D]%7D){target="_blank"}
* [WUCC - Simon Turner-Bottomley Freshers' Competition](https://www.facebook.com/events/1248156635336860/?acontext=%7B%22event_action_history%22%3A[%7B%22surface%22%3A%22group%22%7D]%7D){target="_blank"}
* Warwick Mountains Elections
* WUCC Tour - Usually to [Spain](https://www.facebook.com/events/1555131704562732/?acontext=%7B%22event_action_history%22%3A[%7B%22surface%22%3A%22group%22%7D]%7D){target="_blank"} or [Italy](https://www.facebook.com/events/2169123249774212/?acontext=%7B%22event_action_history%22%3A[%7B%22surface%22%3A%22group%22%7D]%7D){target="_blank"}, or even [Turkey](https://www.facebook.com/events/575350565951721/?acontext=%7B%22event_action_history%22%3A[%7B%22surface%22%3A%22group%22%7D]%7D){target="_blank"}

## Term 3
* WUCC Elections
* WUCU Elections
* Warwick Mountains Trip - Usually to Scotland