---
title: "Saving Money On Climbing Gear"
description: | 
  The best places in Coventry to buy cheap gear and other cash-saving tips.
keywords:
  - warwick university
  - warwick university climbers union
  - climbing
  - students
  - union
  - outdoor climbing
  - warwick sport
  - warwick students union
  - cheap
  - equipment
  - gear
  - coventry
  - leamington
  - discounts
  - money saving
output: 
  distill::distill_article:
    css: style.css
---

<style>
body {
text-align: justify}
</style>

# Go Outdoors
There is a [Go Outdoors store](https://www.gooutdoors.co.uk/stores/coventry){target="_blank"} next to Canley station. It is only half an hour walk from campus or alternatively you can catch catch the [free shuttle bus](https://warwick.ac.uk/services/estates/transport/buses/shuttlebus/){target="_blank"} to the station.

Go Outdoors offers a [price match guarantee](https://www.gooutdoors.co.uk/price-guarantee){target="_blank"} where they will beat any price given by another UK based company by 10%. You price match online or in store.

They also do a [10% student discount](https://www.gooutdoors.co.uk/students){target="_blank"} which you get by showing your student card at the checkout.

Note that you may need to buy a Go Outdoors membership card to access these offers. If your flatmate has a discount card then [you are allowed to use that](https://www.gooutdoors.co.uk/discount-card-terms-and-conditions){target="_blank"}.

# Decthalon
Decathlon does own-brand climbing gear which is much cheaper, but of lower quality, than that which you can buy at Go Outdoors. It's a good option for people who want to buy their first pieces of climbing gear and don't want to spend too much. The [Decathlon store](https://www.decathlon.co.uk/store-view/sport-shop-coventry-0070071700717){target="_blank"} is much further away from campus than the Go Outdoors store (15 minute drive/45 minute cycle).

# Lockwoods
[Lockwoods](https://lockwoods.com/) is a speciality outdoor stone in Leamington Spa. They offer a [20% off student discount for WUCC members](https://www.facebook.com/photo?fbid=3532712616790913&set=gm.4467336716669666){target="_blank"}. It should however be noted that gear may still cost more than other places, even with the discount. Notwithstanding, there are several advantages of buying gear from Lockwoods:

1. It is a good option for those who live in Leamington and do not have cars. 
2. The customer service and specific gear knowledge of staff is significantly better than at Go Outdoors and Decathlon.
3. They have a larger range of products available.  

# Other Warwick-Specific Cost Savings
* If you work for Warwick Sport (even if you aren't a member of the climbing team, and even if you are a unitemp) then you are entitled to free access to the climbing wall. This was stated in the 2019 Standard Operating Procedures for Warwick Sport staff, needs verifying for 2021.
* If you are a employee of Sports Centre or a Unitemp you are [permitted to buy a staff car parking permit](https://warwick.ac.uk/services/carparks/permits/non-salaried_staff) (doesn't have to be for your own vehicle). This also gives you access to the staff-only car parks where there is always ample space for vehicles, even when the other car parks are completely full.
* A lot of websites will include postage for free if you reach a certain price threshold. You can take advantage of this by asking your friends or posting on the WUCC or WUCU Facebook groups to see if anyone else wants to get something from the same website, thereby meeting the threshold and having no postage costs to pay.
* [The Ballroom](https://www.ballroomclimbing.co.uk/){target="_blank"} and [Depot Birmingham](https://www.theclimbingdepot.co.uk/birmingham/about){target="_blank"} both sell climbing gear. If you're planning on visiting one of these walls anyway then it can make sense to use the opportunity to try gear on that you're considering buying. It is also possible, though perhaps not likely, they will be cheaper than buying online when you take postage into consideration.
* Both [Hard Wood Holds](https://www.hardwoodholds.co.uk/) and [BK Holds](https://www.instagram.com/bk.holds/) are based in Coventry so may be the cheapest option if you are able to save on postage by collecting from them.
* The Sports Hub occasiaonlly throws holds away so it is worth checking with Luke (head-setter) to see if any are available. The Sports Hub has to pay to throw them away so giving them to you may sometimes be mutually beneficial; it's also good for the planet.
* The university recyles wood so if you are keen to make your own holds it may be worth asking the [Waste and Recycling Team](https://warwick.ac.uk/about/environment/recycling/a-z) if you can have any. There are also whispers of a scrap wood bin in the Department of Engineering.

# Other Cheap Gear Options
* [Google Shopping](https://www.google.com/shopping) indexes most of the UK based online gear stores so it is always worth comparing your price against it.
* Facebook marketplace groups [Outdoor Gear Exchange UK](https://www.facebook.com/groups/usedgearexchangeuk/){target="_blank"} and [Climbing Gear Exchange UK](https://www.facebook.com/groups/733963366659553){target="_blank"} are places where people commonly sell second hand climbing gear. See below for which items to avoid.
* [Rock + Run](https://rockrun.com/){target="_blank"} are known for occasionally having very good deals on. They are always worth checking.
* [Cotswold Outdoor](https://www.cotswoldoutdoor.com/our-partners/bmc.html){target="_blank"}, [Up and Under](http://www.upandunder.co.uk/Blog/archive/2013/12/bmc-discount-code/){target="_blank"}, [Snow + Rock](https://www.snowandrock.com/?utm_source=PartnerPage&utm_campaign=BMC&utm_medium=Website){target="_blank"} and [Absolute Snow](https://www.absolute-snow.co.uk/services/partners-programme-club-discounts) offer a 15% discount to BMC members. This discount can sometimes make one of these the cheapest option. If you are a paid up member of either WUCC or WUCU you are also a member of the BMC by affiliation. See the [BMC website](https://www.thebmc.co.uk/get-discounts-in-shops-nationwide){target="_blank"} a full list of stores where you can get a BMC discount. 
* [eBay](https://www.ebay.co.uk/sch/i.html?_from=R40&_nkw=chalk+bag&_sacat=0&_sop=15&rt=nc&LH_Auction=1){target="_blank"} is a good place to pick up a second hand chalk bag for cheap. For boulderers, the cheapest option is just putting a chalk ball in a sandwich bag.
* If you know what you want and are willing to wait for it then a good strategy is setting a [saved search up with eBay](https://www.ebay.co.uk/help/buying/search-tips/saved-searches?id=4051){target="_blank"} so you'll be notified if the thing you want is listed.
* The [Baoa Negra Knee Pad](https://www.gripz.uk/store/products/bagoa-negra-knee-pad) is a cheaper alternative to Send Knee Pads.  The cheapest option is to wear jeans, the most sticky trouser material, and develop knee callouses and a high pain tolerance.


# Cheap Gear to Avoid
* [Unrated carabiners from Amazon, eBay or eleswhere](https://www.reddit.com/r/climbing/comments/b685vi/new_climbers_do_not_use_amazon_for_gear_unless/){target="_blank"}. For more info on gear ratings, see [this Rock and Ice article](https://rockandice.com/gear/buying-tips/making-sense-of-the-uiaa-ce-and-3-sigma-ratings/){target="_blank"}.
* Second hand rope, harnesses, slings or helmets, [for safety reasons](https://blog.weighmyrack.com/buying-used-climbing-gear/){target="_blank"}. The exception to this is if you trust the seller to accurately confirm the item's age, level of use, and whether it has taken any stress or damage.
* Decthalon chalk because it's rubbish. Rock Technologies chalk is a good cheap option, [available at Go Outdoors](https://www.gooutdoors.co.uk/15899255/rock-technologi-chalk-ball-15899255){target="_blank"} and you can use the student discount.
* [Beemat boulder pads](https://www.beemat.co.uk/collections/bouldering-mats){target="_blank"} absorb so little force that they aren't worth it, even at very low prices.
* There's no need to spend £100 on a Armaid when you can [achieve the same thing with a brick](https://www.youtube.com/watch?v=XFUBjLQZYEc&list=PL3HBwYR2uvsYnCj_49cc9hSj8_sX1GwaY&index=25){target="_blank"}, TV remote or can of beans.

# Borrowing Gear
* You can borrow helmets, bouldering pads and guidebooks from WUCC (paying a deposit), but make sure to look after them and to give them back!
* During club hours you can also borrow shoes, harnesses and belay devices from WUCC, however they must be returned afterwards.
* The university library has two books on climbing injury prevention and treatment. [Make Or Break](https://encore.lib.warwick.ac.uk/iii/encore/record/C__Rb3069074__Smake%20or%20break__Orightresult__U__X6?lang=eng&suite=cobalt){target="_blank"} and [One Move Too Many](https://encore.lib.warwick.ac.uk/iii/encore/record/C__Rb3069075__Sone%20move%20too%20many__Orightresult__U__X6?lang=eng&suite=cobalt){target="_blank"}. WUCC also has a copy of One Move Too Many you can borrow.
* The university library has a respectable collection of general [rock climbing](https://encore.lib.warwick.ac.uk/iii/encore/search/C__SRock%20climbing.__Ff%3Afacetmediatype%3Aa%3Aa%3APrint%20Book%3A%3A__Orightresult__X0?lang=eng&suite=cobalt){target="_blank"} and [mountaineering](https://encore.lib.warwick.ac.uk/iii/encore/search/C__SMountaineering.__Ff%3Afacetmediatype%3Aa%3Aa%3APrint%20Book%3A%3A__Orightresult__X0?lang=eng&suite=cobalt){target="_blank"} books.
