---
title: "The WUCU Manifesto"
keywords:
  - warwick university
  - climbing
  - students
  - union
  - manifesto
  - outdoor climbing
  - costs
  - price
  - warwick sport
  - warwick students union
---

<style>
body {
text-align: justify}
</style>

The Warwick University Climbers’ Union exists in response to Warwick Students' Union (SU) and Warwick Sport erecting substantial financial barriers in the way of student participation in sport. These organisations hold access to sport hostage and demand large sums of money from students by exploiting their passion for their sports. The cost of joining an affiliated sports club has become prohibitively high for many students and has created substantial inequalities in access to sport, with only those from economically privileged backgrounds able to afford the costs of participation. 

At the same time, the affiliated sports clubs are given almost none of this money back in funding. In 2017, Warwick Sport introduced the club pass which demands [a further £66 from students](https://theboar.org/2020/06/petition-launched-stop-increase-warwick-sport-club-pass/) who would like to belong to a sports club; this is on top of the [£32 Sports Federation Fee](https://www.warwicksu.com/societies-sports/sports-clubs/howtojoin/) payable to Warwick SU. In the 2020/1 academic year, [the total cost of joining Warwick University Climbing Cub (WUCC) is £120.85](price.html). £104 of this is paid to Warwick Sport and Warwick SU and of which WUCC recieves less than £6 back in funding per person. Since 2015 the cost of a climbing membership has [increased by £70](https://web.archive.org/web/20150912031957/http://www2.warwick.ac.uk/services/sport/memberships/student/) to £210 and an additional yearly registration fee of £6 has been introduced. This means that climbing membership fees [take up between 4-8% of a student's yearly maintanance loan](https://www.savethestudent.org/student-finance/maintenance-loans.html). This is without considering the costs of equipment and trips.

If you do not already know how to climb then this could very well be good value for money, as the WUCC executive committee organise free climbing lessons. The joining fees [are less than the cost of climbing lessons from a company such as Warwick Sport](https://warwick.ac.uk/services/sport/active/climbing). However if you already know how to climb then the cost of joining WUCC is simply not value for money, in addition to being unaffordable. Faced with these fees, and having already paid high membership fees for indoor climbing, many experienced climbers simply do not have any reason to join WUCC even if they can afford to. Mosts students do not have cars and so paying for WUCC membership to go on trips is one of the only ways students are able to go climbing outside. Pricing students out of WUCC membership in effect prices students out of access to climbing outdoors and out of [the positive mental health effects that being in nature brings](https://journals.sagepub.com/doi/pdf/10.1177/1359105320977642). 

It is clear that these fees are prohibitive. The solution to this problem is an organisation which will run outdoor climbing trips that is unaffiliated with Warwick SU and Warwick Sport. Members of the unaffiliated organisation would not have to pay the extortionate Sports Federation or Club Pass fees. The elimination of these costs means students are more likely to be able to afford to climb both indoors and outdoors. This organisation would also give students who are priced out of WUCC membership something they can afford to belong to and to provide them with a sense of community.

**This is our mission: to be an organisation which facilitates access to outdoor climbing for students regardless of their economic circumstances or background.**