---
title: "Quick-Drying Crags"
description: | 
  Options for getting outside soon after rain.
output: 
  distill::distill_article:
    css: style.css
---

Crags which are exposed to the wind and are south facing dry fastest. A crag will dry fastest if the wind is high and blowing directly onto it. If the humidity is in the 90%+ range then it is likely there is fog or mist sitting over the crag and this can mean that it won't dry. Remember [not to climb on wet sandstone or gritstone](https://www.ukclimbing.com/articles/skills/series/respecttherock/chalk_use-9892) as this will permanently damage the rock.

[The Met Office](https://www.metoffice.gov.uk/) are the best source for weather data and they get the forecast right more often than not. It's worth downloading the smartphone app and storing these crag locations so you can easily compare the forecasts on wet-looking weekends.

# Peak District
### The Eastern Edges
Stanage and Derwent Edge dry the fastest out of the Eastern Edges, followed by Burbage. The exception to this is if fog and mist is sitting over these higher edges, in which case [Curbar](https://www.ukclimbing.com/logbook/crag.php?id=21) dries fastest, followed by [Froggatt](https://www.ukclimbing.com/logbook/crags/froggatt_edge_derbyshire-22) and [Birchen](https://www.ukclimbing.com/logbook/crags/birchen_edge-94). The forecast for Stanage is named [High Neb](https://www.metoffice.gov.uk/weather/forecast/gcqzd69kf). The best forecast for Curbar etc. is [Chatsworth House](https://www.metoffice.gov.uk/weather/forecast/gcqyg6gsh).

### The Western Edges
[The Roaches](https://www.ukclimbing.com/logbook/crags/roaches_upper_tier-797) and [Hen Coud](https://www.ukclimbing.com/logbook/crag.php?id=899#maps) are on the Western Side of the Peak District. They face south west. The upper tier of the Roaches dries very very quickdry due to its exposure to the wind, the lower tier takes a lot longer to dry. It can be the case that the Eastern Edges are wet but the Roaches are dry, and vice versa. The Roaches has [its own weather forecast](https://www.metoffice.gov.uk/weather/forecast/gcqw6rxvc).

### The Limestone
The main wall at [Horseshoe Quarry](https://www.ukclimbing.com/logbook/crags/horseshoe_quarry-148) dries reasonably quickly. [Harpur Hill](https://www.ukclimbing.com/logbook/crags/harpur_hill_quarry-956) gets a lot of wind but not a lot of sun. A lot of the overhanging limestone crags [will stay dry in the rain](weatherproof_crags.html).

# Wye Valley
### Wyndcliff Quarry
[Wyndcliff Quarry](https://www.ukclimbing.com/logbook/crags/wyndcliff_quarry-2731) is a good sport climbing option when the Peak is soaked and is the first crag to dry after rain in the Wye Valley. It faces South West and gets all the sun going. It is exposed to the wind if it is blowing in the right direction. The nearest forecast is for [Chepstow](https://www.metoffice.gov.uk/weather/forecast/gcnjg1jby).

# Leicestershire
### Beacon Hill
[Beacon Hill](https://www.ukclimbing.com/logbook/crags/beacon_hill_leicestershire-1170) is very exposed to the wind and sun. There is vegetation to retain moisture above the crag, an now trees below it to shield it from the wind and sun. The rock is volcanic and does not absorb moisture. As a result Beacon Hill dries almost instantly. The nearest forecast is for [Copt Oak Youth Hostel](https://www.metoffice.gov.uk/weather/forecast/gcr5fgdhm).

# Nottinghamshire
### Pleasley Vale
[Pleasley Vale](https://www.ukclimbing.com/logbook/crags/pleasley_vale-1378) faces south and if sun follows rain you can watch it dry before your eyes. It's also fairly overhanging so the bouldering may stay dry and you can get on that while the trad routes dry out. The nearest forecast is for [Mansfield Woodhouse](https://www.metoffice.gov.uk/weather/forecast/gcrnkywg8).