---
title: "The Cheapest Ways to Try Out Climbing"
description: | 
  How to get your first taste of climbing for as cheap as possible.
output: 
  distill::distill_article:
    css: style.css
---

<style>
body {
text-align: justify}
</style>
  

## Through WUCC
### The Sport and Wellness Hub

Any student can try out climbing once for absolutely free, although the mechanisms to do this aren’t always straightforward. In previous years students have been able to book onto a “Taster” session which lasts 20 minutes and gives a good taste of what climbing is about. This year the club was not allowed to run tasters. 

If you miss the WUCC taster sessions at the start of term then you can still try climbing on campus, though it will cost some money and some of your sanity. I’ll go into registration briefly here as if you’re a club member it could save you £9. Before you leave the floor, you must have completed the [registration process](https://warwick.ac.uk/services/sport/active/climbing/#register). This breaks down into filling out a from, watching a video, paying the annual registration fee of £6 and having an in person floor walk. On the online booking system you can book an “induction” for £12 or £15 which includes entry to the wall, gear hire and the floor walk (it’s just a member of staff giving you a 5 min safety lecture). Of course, if you are a club member you don’t need to pay for entry or gear hire during club hours, so make sure you don’t book a "induction", just book onto the regular club session - details on [the WUCC Website](https://warwickclimbing.co.uk/about/clubhours/).

### The Ballroom 

[The Ballroom](https://www.ballroomclimbing.co.uk/) is located in Coventry city centre. Last year the club had a one off deal where students could climb at the Ballroom for just £2. It was a very well received event and this is something next year’s presidents will definitely be looking to bring back.

## Not Through WUCC 
### The Sport and Wellness Hub

<WIP>
Registration at the [Sport and Wellness Hub](https://warwick.ac.uk/services/sport/active/climbing/#register) is £6, then entry is £6.50 off-peak or £9.50 on-peak. You will also need to rent climbing shoes. Paying these fees allows you to use the bouldering wall (the shorter walls above crash mats where there are no ropes). If you want to try roped climbing then you can pay £34 for the staff to give you a taster session (this price drops if more than one of you is doing a taster) and £6 for registration. No discounts are available for students. Note from a Sports and Wellness Hub perspective there’s no difference between trying climbing and just going for a climb, so these prices are what any regular climber would pay for entrance.

### The Ballroom

[The Ballroom](https://www.ballroomclimbing.co.uk/) is located in Coventry city centre. Registration at the Ballroom costs £3 and entry is £7.50 for students. You will need to rent climbing shoes which also costs £3. A return bus ticket into Coventry costs £3.30. If you drive then the nearest car-park is Bishop Street; it costs £1 to park here after 6PM and on Sundays (see [here](https://www.coventry.gov.uk/directory_record/11432/bishop_street_tower_street_car_park) for prices at other times).

### Flash Climbing

[Flash Climbing](https://flashclimbingcentre.co.uk/) is located in Solihull but a good option for those with cars. 30 minutes drive from Leamington Spa, 25 from Kenilworth, 20 from campus. Entry for students is £6 and shoe hire is £2. There are no registration fees. 

### Leamington Clip N Climb
If you're just looking for a laugh and aren't wanting to do serious climbing then you may wish to consider the [Clip N Climb at the Newbold Comyn Leisure Centre](https://www.everyoneactive.com/centre/newbold-comyn-leisure-centre/?activitySearch=Clip%20n%20climb). It's designed for kids but adults are allowed to try it too. Peak price is £8 and off-peak is £12.50. Much less serious but much, much cheaper than the Sport and Wellness Club.
