---
title: "Weather-Proof Crags"
description: | 
  Locations where you climb outside despite the rain.
keywords:
  - warwick university
  - warwick university climbers union
  - climbing
  - students
  - union
  - outdoor climbing
  - warwick sport
  - warwick students union
  - weather-proof crags
  - rain
output: 
  distill::distill_article:
    css: style.css
---

This article details the outdoor options available to University of Warwick students when it is, or has been, raining. There are two classes of weather-proof venues. The first are steep and overhanging crags that are typically home to hard boulder problems and sport climbs. The second are artificial structures with ceilings, such as bridges and buildings. 

# Weather-Proof Crags
### Forest Rock, Charnwood, Leicestershire
[Forest Rock](https://www.ukclimbing.com/logbook/crags/forest_rock-1171) is a cave tucked away in the sleepy town of Woodhouse Eaves. The problems from Sorcerer to Sorceress are permanently dry aside from some dryable drips. The problems further into the cave are more uncertain, sometimes they can be bone dry despite recent torrential rain and sometimes they can be inexplicably wet during a dry spell. Luckily Forest Rock is only 45 minutes from campus so it's not the end of the world if it's wet. There is usually something to do that is dry and worse comes to worst you can always drive over to [Rothley Brook Bridge](https://www.ukclimbing.com/logbook/crags/rothley_brook_bridge-25960) for some truly perma-dry action.

### Wright's Rock, Churnet Valley, Staffordshire
[Wright's Rock](https://www.ukclimbing.com/logbook/crag.php?id=904) is a good option if it's forecast to rain but less good if it has been lashing it down for a few days as significant drips will write off whole problems. Gentleman's Rock down in [Dimming's Dale](https://www.ukclimbing.com/logbook/crags/dimmings_dale-21703) is a similar option.

### Biblins Cave, Forest of Dean, Herefordshire
[Biblins Cave](https://www.ukclimbing.com/logbook/crags/biblins_cave-20666) is a large limestone cave. Unfortunately it is only open from 1st May to 30th September. Pop For The Top does get wet from rain but the other problems don't get wet other than from condensation. 

### Raven Tor, Peak District, Derbyshire
[Raven Tor](https://www.ukclimbing.com/logbook/crags/raven_tor_millers_dale-146) is reliably dry once it has dried out in Spring, but iffy in late Autumn and Winter. Much of the sport climbing will stay dry in the rain during the summer too. Ben's Roof is famous for being climbable no matter the conditions. [Blackwell Dale](https://www.ukclimbing.com/logbook/crag.php?id=965) is also worth a look as you drive past it on the way to Raven Tor from Coventry. 

### Water-Cum-Jolly (Rubicon), Peak District, Derbyshire
The routes around the roof of [Rubicon](https://www.ukclimbing.com/logbook/crag.php?id=140#maps) are reliably dry but the approach area can go underwater if there has been a deluge. Kudos Wall stays dry in the rain and the floor is higher than the approach, so if you have some wellies to get past the flooded approach it can be a good option. but if it rains enough it will get wet from runoff. In very wet periods even the wall under Kudos can flood. The [River Wye GaugeMap](https://www.gaugemap.co.uk/?fbclid=IwAR0nQ9bSNGCOSKNVHkBpbZTpL6i8pY7VHmDkfWeVEcQoUtLISPp1OZ8nyZY#!Map/Summary/131/137) keeps track of the river level and will indicate if the river has flooded.

### Anston Stones Wood, South Yorkshire
Bits of [Anston Stones Wood](https://www.ukclimbing.com/logbook/crags/anston_stones_wood-953) are reliable. Dark Art roof never gets wet from rain. Ebola Buttress and Wave Wall will stay dry in the rain but suffer from seepage.

### Ippikins Rock, Wenlock Edge, Shropshire
[Ippikins Rock](https://www.ukclimbing.com/logbook/crags/ippikins_rock-1067) was once [fully developed as a bouldering crag](https://ukbouldering.com/board/index.php/topic,15156.msg310418.html#msg310418) but the topo is now unavailable. The best line is [Karfi f7C](https://www.youtube.com/watch?v=rZLCGfMzYAM). Included here because I reckon the bouldering here would stay dry in the rain.  Worth a look on a dry day to see if you want to gamble on it down the line.


# Artificial Structures
### Robo's Bridge, Marston Green, West Midlands
[Robo's Bridge](https://www.ukclimbing.com/logbook/crags/robos_bridge-21639) is a convenient bouldering location very close to campus. The 'rock' stays dry but if it's windy the rain can blow in and soak your pads. Only 15 mins from campus and the problems are surprisingly good considering the medium.

### Rothley Brook Bridge, Charnwood, Leicestershire
[Rothley Brook Bridge](https://www.ukclimbing.com/logbook/crags/rothley_brook_bridge-25960) is home to a perma-dry layback crack problem. Three star movement, zero star location. Worth visiting if you get rained off something in Leicestershire but don't have the beans for Forest Rock.

### The Engineering Department, University of Warwick
Several surprisingly good problems around the [Engineering Department](https://www.ukclimbing.com/logbook/crags/warwick_sport_rock_garden-24998). Permanently dry and floodlit. One for the first year to get done while still in halls or for the car-less to do while wishing they had learned to drive in sixth form. 


```{r, echo=FALSE, results = 'asis'}  
library(leaflet)

hill_icons <- icons(
  iconUrl = "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/twitter/259/mountain_26f0.png",
  iconWidth = 30, iconHeight = 30
)

bridge_icons <- icons(
  iconUrl = "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/facebook/65/bridge-at-night_1f309.png",
  iconWidth = 30, iconHeight = 30
)

building_icons <- icons(
  iconUrl = "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/samsung/265/office-building_1f3e2.png",
  iconWidth = 30, iconHeight = 30
)

uni_icons  <- icons(
  iconUrl = "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/joypixels/257/graduation-cap_1f393.png",
  iconWidth = 30, iconHeight = 30
)

leaflet() %>%
  addTiles() %>%  # Add default OpenStreetMap map tiles
  addMarkers(lat=51.83470, lng=-2.65850, popup="Biblins Cave <br> Type: Crag <br> Rocktype: Limestone", icon = hill_icons) %>%
  addMarkers(lat=52.72285, lng=-1.21504, popup="Forest Rock <br> Type: Crag <br> Rocktype: Slatey Tuff", icon = hill_icons) %>%
  addMarkers(lat=52.98562, lng=-1.90854, popup="Wright's Rock <br> Type: Crag <br> Rocktype: Sandstone", icon = hill_icons) %>%
  addMarkers(lat=53.25626, lng=-1.77604, popup="Raven Tor <br> Type: Crag <br> Rocktype: Limestone", icon = hill_icons) %>%
  addMarkers(lat=53.25120, lng=-1.75140, popup="Water-Cum-Jolly (Rubicon) <br> Type: Crag <br> Rocktype: Limestone", icon = hill_icons) %>%
  addMarkers(lat=53.34410, lng=-1.20870, popup="Anston Stones Wood <br> Type: Crag <br> Rocktype: Limestone", icon = hill_icons) %>%
  addMarkers(lat=52.56420, lng=-2.63580, popup="Ippikins Rock <br> Type: Crag <br> Rocktype: Limestone", icon = hill_icons) %>%
  addMarkers(lat=52.46900, lng=-1.75940, popup="Robo's Bridge <br> Type: Bridge <br> Rocktype: Red Brick", icon = bridge_icons) %>%
  addMarkers(lat=52.71442, lng=-1.12540, popup="Rothley Brook Bridge <br> Type: Bridge <br> Rocktype: Concrete", icon = bridge_icons) %>%
  addMarkers(lat=52.38261, lng=-1.56117, popup="Engineering Department <br> Type: Building <br> Rocktype: Blue Brick", icon = building_icons) %>%
  addMarkers(lat=52.37778, lng=-1.5699, popup="University of Warwick", icon = uni_icons)



```
